### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/infografia-de-las-librerias-IsaacCS1#2]
[INFOGRAFIA LIBRERIAS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-IsaacCS1/files/8221298/INFOGRAFIA.LIBRERIAS.pdf)

**Comment by IrvingFernand0** [comment]
Esta actividad obtuvo 98% de puntos
Correspondiente a **19.6** de calificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
